name: Deploy to Fly.io

on:
  push:
    branches:
      - CICD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Usa la última versión de checkout
      - name: Checkout code
        uses: actions/checkout@v4 # Actualizado a la última versión estable

      # Usa la última versión de setup-node
      - name: Set up Node.js
        uses: actions/setup-node@v3 # Actualizado a la última versión estable
        with:
          node-version: "20" # Actualiza a Node.js 20, según las advertencias

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to Fly.io
        run: flyctl deploy
